# Generated by Django 5.2.1 on 2025-05-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.IntegerField(choices=[(1, 'breakfast'), (2, 'lunch'), (3, 'snack')]),
        ),
    ]
