# Generated by Django 5.2.1 on 2025-05-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_alter_meal_type'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='products',
            field=models.ManyToManyField(related_name='meals', to='product.products'),
        ),
    ]
