# Generated by Django 5.2.1 on 2025-05-25 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='children',
            name='raw_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
