# Generated by Django 5.2.1 on 2025-05-27 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_children_created_at_children_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='childgroup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
