# Generated by Django 5.2.1 on 2025-05-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_childgroup_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childgroup',
            old_name='created_at',
            new_name='data',
        ),
    ]
