# Generated by Django 5.2.1 on 2025-05-27 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_rename_created_at_childgroup_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childgroup',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
