# Generated by Django 5.2.1 on 2025-05-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_alter_childgroup_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='children.childgroup'),
        ),
    ]
