# Generated by Django 5.2.1 on 2025-05-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyReports',
        ),
    ]
